DESTINATIONS = [
  "platform=iOS Simulator,name=iPhone 6,OS=8.4",
  "platform=iOS Simulator,name=iPhone 6,OS=9.3",
  "platform=iOS Simulator,name=iPhone 6,OS=10.0",
]

namespace :test do
  task :iphonesimulator do
    DESTINATIONS.each do |destination|
      command = "xcodebuild -scheme 'TAKKitSwiftSample' -workspace TAKKitSwiftSample.xcworkspace -destination '#{destination}' -sdk iphoneos test"
      puts command
    end
  end
end
